api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path(
        "comments/<str:board>/<str:no>/", views.CommentList.as_view(),
        name="comments"
    ),

    path(
        "latest/comment/<str:board>/<str:no>/",
        views.LatestComment.as_view(),
        name="latest_comment",
    ),
]

chan13/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/', include('api.urls')),
]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .import views


app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('board/<str:board>/', views.BoardView.as_view(), name='board'),
    path('create-post/<str:board>/', views.PostCreationView.as_view(),
         name='create_post'),
    path('post/<str:board>/<str:no>/', views.PostView.as_view(), name='post'),
]

api/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.urls import reverse
from django.utils.crypto import get_random_string
from django.utils import timezone
from django.utils.text import slugify
from PIL import Image


def get_unique_id(model, post=True):
    random_string = slugify(get_random_string(10))
    if post:
        while model.posts.filter(no=random_string).exists():
            random_string = slugify(get_random_string(10))
    else:
        while model.comments.filter(no=random_string).exists():
            random_string = slugify(get_random_string(10))
    return random_string


class Board(models.Model):
    name = models.CharField(max_length=100, unique=True)
    banner = models.ImageField(upload_to="banners")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("main:board", args=[self.name])


class Post(models.Model):
    name = models.CharField(max_length=30, blank=True)
    title = models.CharField(max_length=50)
    body = models.TextField()
    image = models.ImageField(upload_to="post_images")
    no = models.SlugField(max_length=10, unique=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    last_activity = models.DateTimeField(default=timezone.now)
    board = models.ForeignKey(Board, on_delete=models.CASCADE,
                              related_name="posts")

    class Meta:
        ordering = ["-last_activity"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("main:post", args=[self.board.name, self.no])

    def save(self, *args, **kwargs):
        if not self.no:
            self.no = get_unique_id(self.board)
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 600 or img.width > 600:
            out_size = (600, 600)
            img.thumbnail(out_size)
            img.save(self.image.path)


class Comment(models.Model):
    body = models.TextField()
    image = models.ImageField(upload_to="comment_images", blank=True)
    no = models.SlugField(max_length=10, unique=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name="comments")
    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True,
                               blank=True, related_name="replies")

    class Meta:
        ordering = ["created"]
        get_latest_by = 'created'

    def save(self, *args, **kwargs):
        if not self.no:
            self.no = get_unique_id(self.post, post=False)
            self.post.last_activity = timezone.now()
            self.post.save()
        super().save(*args, **kwargs)
        if self.image:
            img = Image.open(self.image.path)
            if img.height > 500 or img.width > 600:
                out_size = (500, 600)
                img.thumbnail(out_size)
                img.save(self.image.path)

main/forms.py
from django.forms import ModelForm
from django import forms
from .models import Post


class PostCreationForm(ModelForm):
    name = forms.CharField(max_length=30, required=False, help_text="Your nickname[optional]")
    class Meta:
        model = Post
        fields = ['name', 'image', 'title', 'body']

api/views.py
from django.shortcuts import get_object_or_404
from rest_framework import generics
from .serializers import CommentSerializer
from main.models import Board, Post, Comment


class CommentList(generics.ListCreateAPIView):
    serializer_class = CommentSerializer

    def get_queryset(self):
        board = get_object_or_404(Board, name=self.kwargs["board"])
        post = get_object_or_404(Post, no=self.kwargs["no"], board=board)
        return post.comments.all()

    def perform_create(self, serializer):
        board = get_object_or_404(Board, name=self.kwargs["board"])
        post = get_object_or_404(Post, no=self.kwargs["no"], board=board)
        serializer.save(post=post)


class LatestComment(generics.RetrieveAPIView):
    serializer_class = CommentSerializer

    def get_object(self, **kwargs):
        board = get_object_or_404(Board, name=self.kwargs["board"])
        post = get_object_or_404(Post, board=board, no=self.kwargs["no"])
        return post.comments.latest()

main/views.py
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404, reverse
from .models import Board, Post
from .forms import PostCreationForm


class HomeView(TemplateView):
    template_name = "main/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Recent_Posts"] = Post.objects.annotate(Count("comments")).order_by('-last_activity')[:12]
        return context


class BoardView(ListView):
    model = Post
    paginate_by = 12
    template_name = "main/board.html"
    context_object_name = "Posts"

    def get_queryset(self):
        board_name = self.kwargs["board"]
        self.board = get_object_or_404(Board, name=board_name)
        return self.board.posts.annotate(Count("comments")).order_by('-last_activity')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["board"] = self.board
        return context


class PostView(DetailView):
    model = Post
    context_object_name = "Post"
    template_name = "main/post.html"

    def get_object(self):
        board = get_object_or_404(Board, name=self.kwargs["board"])
        self.post = get_object_or_404(Post, no=self.kwargs["no"], board=board)
        return self.post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["Comments"] = self.post.comments.all()
        return context


class PostCreationView(CreateView):
    model = Post
    template_name = "main/create-post.html"
    form_class = PostCreationForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        board = get_object_or_404(Board, name=self.kwargs['board'])
        obj.board = board
        obj.save()
        return HttpResponseRedirect(reverse('main:board',
                                            args=[self.kwargs['board']]))

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %} {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <style>
    .card-img{
      width: 150px!important;
      height: 100px!important;
      object-fit: cover;
   }
  </style>
</head>
<body style="background-color:black">
<nav class="navbar navbar-expand-lg navbar-light bg-dark" style="justify-content:center;">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li class="nav-item">
      <a class="nav-link" href="/" style="color:PaleGreen">home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/board/science" style="color:PaleGreen">science</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/board/technology" style="color:PaleGreen">technology</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/board/entertainment" style="color:PaleGreen">entertainment</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/board/war" style="color:PaleGreen">war</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/board/mystry" style="color:PaleGreen">mystry</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/board/news" style="color:PaleGreen">news</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/board/bangladesh" style="color:PaleGreen">bangladesh</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/board/memes" style="color:PaleGreen">memes</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/board/random" style="color:PaleGreen">random</a>
    </li>
  </ul>
    </div>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

main/templates/main/board.html
{% extends 'main/base.html' %}
{% load humanize %}
{% block title %}
<title>{{board.name}}</title>
{% endblock %}

{% block body%}

<div class="container p-5 my-5 text-black">
  <center>
    <img class="img-fluid" src="{{board.banner.url}}" height="500px" width="300px">
    <br>
    <h4 style="color:crimson">board/{{board.name}}</h4>
    <br>
  <a href="{% url 'main:create_post' board=board.name %}">
  <button class="btn btn-outline-primary">Start A New Thread</button>
  </a>
  </center>
  <br>
  <div class="row" align="center">
  {% for post in Posts %}
  <div class="col-sm-3 p-3 bg-transparent text-black">
    <div class="card border-success mb-3 bg-dark">
      <a  href="{{post.get_absolute_url}}" class="card-title" style="text-decoration: none;">{{post.title|truncatechars:30}}</a>
      <div class="row g-0">
        <div class="col-md-6">
          <img  class='card-img' src="{{post.image.url}}" style="margin:7px;">
        </div>
        <div class="col-md-6">
          <div class="card-header">
            <a href="{% url 'main:board' board=post.board.name %}" class="btn btn-outline-secondary">{{post.board.name}}</a>
          </div>
          <div class="card-body">
            {% if post.name %}
              <p class="card-title">Posted By: {{post.name}}</p>
            {% endif %}
            <p class="card-text" style="color:lavender">{{post.body|truncatechars:20}}</p>
          </div>
        </div>
      </div>
      <div class="row g-0">
        <div class="col-md-6">
          <div class="card-footer">
            <small class="text-muted">{{post.comments__count}} Comments</small>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card-footer">
            <small class="text-muted">{{post.created|naturaltime}}</small>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  </div>

    <br><br>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current" style='color:PaleGreen'>
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div>
{% endblock %}

main/templates/main/create-post.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags % }

{% block title %}
<title>Start A New Thread</title>
{% endblock %}

{% block body%}

<div class="container p-5 my-5 text-white bg-dark">
  <center>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table border="1">
    {{ form}}
  </table>
    <br>
    <button type="submit" class="btn btn-outline-primary">Post</button>
  </form>
  </center>
</div>
{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %}
{% load humanize %}
{% block title %}
<title>Chan</title>
{% endblock %}

{% block body%}
<div class="container p-5 my-5 bg-transparent text-black" align="center">
  <div class="row" align="center">
  {% for post in Recent_Posts %}
  <div class="col-sm-3 p-3 bg-transparent text-black">
    <div class="card border-success mb-3 bg-dark">
      <a  href="{{post.get_absolute_url}}" class="card-title" style="text-decoration: none;">{{post.title|truncatechars:30}}</a>
      <div class="row g-0">
        <div class="col-md-6">
          <img  class='card-img' src="{{post.image.url}}" style="margin:7px;">
        </div>
        <div class="col-md-6">
          <div class="card-header">
            <a href="{% url 'main:board' board=post.board.name %}" class="btn btn-outline-secondary">{{post.board.name}}</a>
          </div>
          <div class="card-body">
            {% if post.name %}
              <p class="card-title">Posted By: {{post.name}}</p>
            {% endif %}
            <p class="card-text" style="color:lavender">{{post.body|truncatechars:20}}</p>
          </div>
        </div>
      </div>
      <div class="row g-0">
        <div class="col-md-6">
          <div class="card-footer">
            <small class="text-muted">{{post.comments__count}} Comments</small>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card-footer">
            <small class="text-muted">{{post.created|naturaltime}}</small>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  </div>
</div>

{% endblock%}

main/templates/main/post.html
{% extends 'main/base.html' %}
{% load humanize %}

{% block title %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<style>
div.sticky {
  position: -webkit-sticky;
  position: sticky;
  top: 0;
  float:right;
  background-color: ivory;
  padding: 5px;
  font-size: 15px;
}

.comment-parent {
  color: crimson;
}

.comment-no {
  color: blue;
}

.comment-body {
  color: PaleGreen;
}
</style>
<title>{{Post.title}}</title>
{% endblock %}

{% block body%}
<div class="container p-5 my-5 bg-dark">
    <center>
    <img src="{{Post.image.url}}" class="img-thumbnail" height='300' width='500'><br>
    <p class="post-no" id="{{Post.no}}" style="color:blue"><u>No.{{Post.no}}</u></p>
    {% if Post.name %}
        <p style="color:tomato">Created By: {{Post.name}}</p>
    {% endif %}
    <p style="color:crimson">{{Post.created|naturaltime}}</p>
    <h4 style="color:slateblue">{{Post.title}}</h4>
    <p style="color:PaleGreen">{{Post.body}}</p>
    </center>
</div>

<div class="container sticky-top bg-dark text-white" style="display:none; width:30%;" id="form-holder">
  <center>
    <form method="post" class="ajax" enctype="multipart/form-data" id="comment_up_form">
        {% csrf_token %}
        <p>Add A Comment</p>
        <p id="replying_to"></p>
        <label for="image" class="form-label" required='false'>Image[optional]</label>
        <input type="file" class="form-control" name="image" id="image">
        <br>
        <label for="comment" class="form-label">comment</label><br>
        <textarea class="form-control" rows="5" id="comment" name="body"></textarea>
        <input type="hidden" id="no" name="parent"><br>
        <button type="submit" class="btn btn-outline-primary" id="comment_submit">Post</button>
    </form>
    <br>
    <button class="btn btn-outline-danger" id='cancel_button'>Cancel</button>
    <br>
  </center>
</div>


<div class="container p-5 my-5">
    <br>
    <ul class="list-group" id="comment_list">
    {% for comment in Comments %}
        <li class="list-group-item bg-dark" >
            <center>
            {% if comment.image %}
                <img src="{{comment.image.url}}" class="img-fluid" height='300' width='500'>
            {% endif %}
            {% if comment.parent %}
                <p class='comment-parent'>Replying to:{{comment.parent.no}}</p>
            {% endif %}
            <p class="comment-no" id="{{comment.no}}"><u>No.{{comment.no}}</u></p>
            <p class='comment-body'>{{comment.body}}</p>
            <center>
        </li>
        <br>
    {% endfor %}
    </ul>
    <script>
        $(document).ready(function(){
        $(".comment-no").click(function(){
            let id = ($(this).attr('id'));
            $("#form-holder").attr("style", "display:block");
            $("#no").val(id);
            $("#replying_to").text("Replying to: "+id);
        });
        $(".post-no").click(function(){
            $("#form-holder").attr("style", "display:block");
            $("#replying_to").text("");
        });

        $("#cancel_button").click(function(){
          $("#form-holder").attr("style", "display:none");
      });

  $("#comment_up_form").submit(function (e) {
    e.preventDefault();
    $.ajax({
      type: "POST",
      enctype: 'multipart/form-data',
      url: "{% url 'api:comments' board=Post.board.name no=Post.no %}",
      headers: {'X-CSRFToken': '{{ csrf_token }}', 'Accept':'application/json'},
      contentType: false,
      processData: false,
      data: new FormData($('#comment_up_form')[0]),
      success: function () {
        $.get("{% url 'api:latest_comment' board=Post.board.name no=Post.no %}", function(data, status){
          $("#form-holder").attr("style", "display:none");
          if(data.image && data.parent)
          {
            $("#comment_list").append("<li class='list-group-item bg-dark' align='center'><img class='img-fluid' src="+ data.image+ ">"+"<p class='comment-parent'>"+'Replying to: '+data.parent+"</p>"+"<p class='comment-no'>"+ "No."+data.no+"</p>" + "<p class='comment-body'>" +data.body+"</p>" +"</li>");
          }
          else if(data.image){
          $("#comment_list").append("<li class='list-group-item bg-dark' align='center'><img class='img-fluid' src="+ data.image+ ">"+"<p class='comment-no'>" + "No."+data.no+"</p>" + "<p class='comment-body'>" + data.body+ "</p>" + "</li>");
          }
          else if(data.parent){
          $("#comment_list").append("<li class='list-group-item bg-dark' align='center'><p class='comment-parent'>" +'Replying to:'+ data.parent +"</p>"+ "<p class='comment-no'>"+ "No." + data.no+ "</p>" +"<p class='comment-body'>" + data.body +"</p>" + "</li>");
          }
          else{
          $("#comment_list").append("<li class='list-group-item bg-dark' align='center'>" + "<p class='comment-no'>"+ "No." + data.no+ "<p class='comment-body'>" + data.body +"</p>" + "</li>");
          }
          $('html, body').animate({scrollTop:$(document).height()}, 'slow');
        });
      }
    });
    return false;
  });
});
</script>
</div>

{% endblock%}